name: internet
channels:
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - bokeh=3.0.3
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - contourpy=1.0.5
  - cryptography=39.0.1
  - decorator=5.1.1
  - executing=0.8.3
  - freetype=2.12.1
  - giflib=5.2.1
  - idna=3.4
  - intel-openmp=2021.4.0
  - ipython=8.10.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.8
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openssl=1.1.1t
  - packaging=22.0
  - pandas=1.5.2
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.3.0
  - pip=22.3.1
  - prompt-toolkit=3.0.36
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - pytz=2022.7
  - pyyaml=6.0
  - readline=8.2
  - requests=2.28.1
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.40.1
  - stack_data=0.2.0
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.7.1
  - tzdata=2022g
  - urllib3=1.26.14
  - wcwidth=0.2.5
  - wheel=0.38.4
  - xyzservices=2022.9.0
  - xz=5.2.10
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - speedtest-cli==2.1.3
